name: Build and Deploy Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [published]

# This job uses RafikFarhad's GitHub action to build and
# push a docker image to a specified GCP repository
jobs:
  build-and-push-api-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # to get all tags

      - name: Generate Image Tag
        id: get-tag
        run: |
          REV=$(git rev-list --tags --max-count=1)
          IMAGE_TAG=$(git describe --tags $REV)
          echo "IMAGE_TAG=${IMAGE_TAG//v}"
          echo "IMAGE_TAG=${IMAGE_TAG//v}" >> $GITHUB_OUTPUT

      - name: Build and Push Image
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          gcloud_service_key: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}
          registry: us-central1-docker.pkg.dev
          project_id: monarch-initiative
          image_name: monarch-api/oai-monarch-plugin
          image_tag: latest, ${{ steps.get-tag.outputs.IMAGE_TAG }}, ${{ github.sha }}
          dockerfile: ./Dockerfile
